name: bugsnag_flutter
description: Unofficial native bindings to the Bugsnag SDK. **Android support is still experimental**.
version: 1.0.0
homepage: https://github.com/greenbits/bugsnag_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 < 3.0.0"

dependencies:
  meta: '>= 1.0.0 <2.0.0'
  flutter:
    sdk: flutter

dev_dependencies:
  matcher: ^0.12.9
  pedantic: any
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.greenbits.bugsnag_flutter
        pluginClass: BugsnagFlutterPlugin
      ios:
        pluginClass: BugsnagFlutterPlugin
